name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo dckr_pat_Bt0PtsbiuCpqx22cecIRmxhoDLw | docker login -u ynadakhivska

    - name: Build Docker image
      run: docker build -t yuliia2205/mysite .

    - name: Push to Docker Hub
      run: docker push yuliia2205/mysite
